# Generated by Django 2.1.2 on 2018-11-15 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20181115_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
    ]
